# Generated by Django 2.1.4 on 2019-01-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=200)),
                ('vender_partno', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('display_begin_date', models.CharField(max_length=200)),
                ('display_end_date', models.CharField(max_length=200)),
                ('hide_product', models.CharField(max_length=200)),
                ('stock_status', models.CharField(max_length=200)),
                ('last_modifies', models.CharField(max_length=200)),
                ('options_cloned_from', models.CharField(max_length=200)),
                ('photos_cloned_from', models.CharField(max_length=200)),
                ('share_stockstatus_with', models.CharField(max_length=200)),
                ('product_keywords', models.CharField(max_length=200)),
                ('product_name_short', models.CharField(max_length=200)),
                ('product_weight', models.CharField(max_length=200)),
                ('free_shipping_item', models.CharField(max_length=200)),
                ('google_product_type', models.CharField(max_length=20000)),
                ('length', models.CharField(max_length=200)),
                ('width', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('ships_by_itself', models.CharField(max_length=200)),
                ('package_type', models.CharField(max_length=200)),
                ('oversized', models.CharField(max_length=200)),
                ('additional_handling_indicator', models.CharField(max_length=200)),
                ('reward_points', models.CharField(max_length=200)),
                ('description_short', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('Notitle1', models.CharField(max_length=2000)),
                ('Notitle2', models.CharField(max_length=2000)),
                ('Notitle3', models.CharField(max_length=2000)),
            ],
        ),
    ]
